#
# /etc/pacman.conf
#
[options]
HoldPkg     = pacman glibc
Architecture = auto
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[kernos]
SigLevel = Optional TrustAll
Server = https://github.com/palazik/linux-kernos/releases/download/kernel

[kernos-calamares]
SigLevel = Optional TrustAll
Server = https://github.com/palazik/linux-kernos/releases/download/calamares

[chaotic-aur]
Server = https://cdn-mirror.chaotic.cx/$repo/$arch

