# SPDX-FileCopyrightText: 2026 palazik
# SPDX-License-Identifier: GPL-3.0-or-later
---
displaymanagers:
  - sddm
  - gdm
  - lightdm
  - greetd
basicSetup: false
sysconfigSetup: false
sddm:
  configuration_file: "/etc/sddm.conf"
lightdm:
  preferred_greeters:
    - lightdm-gtk-greeter.desktop
