# SPDX-FileCopyrightText: 2026 palazik
# SPDX-License-Identifier: GPL-3.0-or-later
---
backend: pacman
skip_if_no_internet: false
update_db: true
update_system: false
pacman:
  num_retries: 2
  disable_download_timeout: true
  needed_only: true

operations:
  - try_remove:
      - calamares
      - kernos-calamares-config
      - archinstall
      - mkinitcpio-archiso
