# SPDX-FileCopyrightText: 2026 palazik
# SPDX-License-Identifier: GPL-3.0-or-later
---
basePackages:
  - base
  - linux
  - linux-firmware
  - amd-ucode
  - intel-ucode
  - sudo
  - networkmanager
  - iwd
  - nano
  - vim
  - less
  - man-db
  - man-pages
  - bash-completion
  - zsh
  - fastfetch
  - dosfstools
  - e2fsprogs
  - exfatprogs
  - f2fs-tools
  - ntfs-3g
  - xfsprogs
  - btrfs-progs
  - cryptsetup
  - lvm2
  - mdadm
  - gptfdisk
  - openssh
  - reflector

postInstallFiles:
  - /etc/pacman.conf
  - /etc/os-release
