# SPDX-FileCopyrightText: 2026 palazik
# SPDX-License-Identifier: GPL-3.0-or-later
---
units:
  - name: "NetworkManager.service"
    action: "enable"
    mandatory: false
  - name: "systemd-timesyncd.service"
    action: "enable"
    mandatory: false
  - name: "sshd.service"
    action: "enable"
    mandatory: false
  - name: "pacman-init.service"
    action: "disable"
    mandatory: false
  - name: "choose-mirror.service"
    action: "disable"
    mandatory: false
