# SPDX-FileCopyrightText: 2026 palazik
# SPDX-License-Identifier: GPL-3.0-or-later
---
unpack:
  - source: "/run/archiso/bootmnt/arch/x86_64/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
    exclude:
      - /etc/calamares
      - /etc/xdg/autostart/kernos-installer*.desktop
      - /home/liveuser/.cache
      - /root/.automated_script.sh
