# SPDX-FileCopyrightText: 2026 palazik
# SPDX-License-Identifier: GPL-3.0-or-later
---
modules-search: [ local ]

instances:
  - id: desktop
    module: packagechooser
    config: packagechooser_desktop.conf
  - id: bootloader
    module: packagechooser
    config: packagechooser_bootloader.conf
  - id: cleanup
    module: shellprocess
    config: shellprocess_cleanup.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - packagechooser@bootloader
      - partition
      - packagechooser@desktop
      - users
      - summary
  - exec:
      - partition
      - mount
      - pacstrap
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - networkcfg
      - hwclock
      - packages
      - displaymanager
      - kernosbootloader
      - services-systemd
      - shellprocess@cleanup
      - umount
  - show:
      - finished

branding: kernos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
